[package]
name = "ohaizac_dev"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
askama = { version = "0.12.0", features = ["with-actix-web"] }
askama_actix = "0.14.0"
serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.4"
